services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env_docker
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - brokerx-net
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  account-service:
      build:
        context: .
        dockerfile: ./account-service/Dockerfile
      container_name: account_service
      ports:
        - "8080:8080"
      env_file: .env_docker
      networks:
        - brokerx-net
      depends_on:
        db:
          condition: service_healthy

  portefeuille-service:
    build:
      context: .
      dockerfile: ./portefeuille-service/Dockerfile
    container_name: portefeuille_service
    ports:
      - "8081:8080"
    env_file: .env_docker
    networks:
      - brokerx-net
    depends_on:
      db:
        condition: service_healthy
      account-service:
        condition: service_started


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - brokerx-net
    depends_on:
      - account-service
      - portefeuille-service

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - brokerx-net
    depends_on:
      - prometheus

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  brokerx-net: