services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env_docker
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: rust_app
    ports:
      - "8080:8080"
    env_file: .env_docker
    stdin_open: true
    tty: true
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - brokerx-net
    depends_on:
      - app

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - brokerx-net
    depends_on:
      - prometheus

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  brokerx-net: