global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:8080']

  - job_name: 'portefeuille-service'
    static_configs:
      - targets: ['portefeuille-service:8080']
